### ISSUE TITLE
TODO: osu!taiko gimmick

### ISSUE THREAD

**Issue by sw1tchbl4d3r** [sw1tchbl4d3r/osu#1]
## Global
- [x] Make Spinners and sliders optional in ppy/osu/pull/18764
       local branch: [classic_drumrolls](https://github.com/sw1tchbl4d3r/osu/tree/classic_drumrolls)
- [x] Make 10k bpm notes hittable in ppy/osu/pull/20510 
       local branch: [high_bpm_judgements](https://github.com/sw1tchbl4d3r/osu/tree/high_bpm_judgements)
- [ ] Add Kiai glow
- [ ] Make Barlines spawn correctly
- [ ] Adjust minimum BPM from 1 to (near) 0
- [ ] Various kinds of hitobject overlaps
- [ ] 0 length sliders

## Classic
- Negative slider length gimmicks, find a way to unite them into one ClassicSlider class.
